sudo: required
services:
  - docker
  
before_install:
  - docker build -t slashuzero/react-test -f ./client/Dockerfile.dev ./client
  
script:
 - docker run slashuzero/react-test npm test -- --coverage
 
after_succes:
  - docker build -t slashuzero/multi-client ./client
  - docker build -t slashuzero/multi-nginx ./nginx
  - docker build -t slashuzero/multi-server ./server
  - docker build -t slashuzero/multi-worker ./worker
  
  #Log in in to the docker CLI
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  #take those images and push them to docker hub
  - docker push slashuzero/multi-client
  - docker push slashuzero/multi-nginx
  - docker push slashuzero/multi-server
  - docker push slashuzero/multi-worker
  
  
deploy:
   edge: true
   provider: elasticbeanstalk
   region: us-east-2
   app: multi-docker
   env: MultiDocker-env
   bucket_name: elasticbeanstalk-us-east-2-842244543224
   bucket_path: docker-multi
   on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
 